apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-simple-app
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.2.30
    helm:
      valueFiles:
      - nginx-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default