apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-simple-app
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: nginx
    targetRevision: 13.2.30
    helm:
      valueFiles:
      - $values/Argocd_Apps/simple-nginx/nginx-values.yaml
  - repoURL: 'https://github.com/mustafa-abdelnasser/FE_CCE_DevOps.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default