apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-default-ssl-cert
  namespace: nginx-ingress
spec:
  dnsNames:
  - ingress.fe.devops-labs.site
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: nginx-default-ssl-cert