apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuard
spec:
  destination:
    name: ''
    namespace: kuard
    server: 'https://kubernetes.default.svc'
  source:
    path: ./argocd-apps/apps/kuard/
    repoURL: 'https://github.com/mustafa-abdelnasser/FE_CCE_DevOps'
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
      env:
        - name: VAULT_ADDR
          value: 'https://vault.devops-labs.site'
        - name: AVP_TYPE
          value: vault
        - name: AVP_AUTH_TYPE
          value: token
        - name: VAULT_TOKEN
          value: "token_value"
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
